package com.datacert.surveysystem.dto;

public enum AnswerType {
  SHORT_TEXT, LONG_TEXT, DATE, DATE_RANGE, MONEY, MONEY_RANGE, INTEGER, INTEGER_RANGE, LOOKUP_LIST, DOCUMENT_UPLOAD, DECIMAL, DECIMAL_RANGE, START, END, RANGE;
}
